apiVersion: v1
data:
  daemon.json: |
    {
      "bip": "192.168.200.1/24"
    }
kind: ConfigMap
metadata:
  name: docker-config
  namespace: actions-runner-system
  
---

apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: fips-runner
  namespace: actions-runner-system
spec:
  replicas: 5
  template:
    metadata:
      labels:
        app: summerwind-runner
    spec:
      dockerdWithinRunnerContainer: true
      organization: FujifilmImagingProductsAndSolutions
# repository level
#     repository: somerepository      
      labels:
        - ranchercluster
      containers:
      - name: runner
        image: summerwind/actions-runner-dind
        volumeMounts:
        - name: docker-config
          mountPath: /etc/docker/       
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - summerwind-runner
              topologyKey: "kubernetes.io/hostname"          
      volumes:
      - name: docker-config
        configMap:
            name: docker-config

# removed, the final version just uses one container with dockerd + runner
#      sidecarContainers:
#      - name: docker
#        image: docker:dind
#        securityContext:
#          privileged: true
#        command: ["dockerd", "--config-file=/etc/docker/daemon.json"]
#        volumeMounts:
#        - name: docker-config
#          mountPath: /etc/docker/
